//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBM.WebForms.SBMServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SBMServiceReference.SendBulkeMailSoap")]
    public interface SendBulkeMailSoap {
        
        // CODEGEN: Generating message contract since element name From from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GDSSendBulkeMail", ReplyAction="*")]
        SBM.WebForms.SBMServiceReference.GDSSendBulkeMailResponse GDSSendBulkeMail(SBM.WebForms.SBMServiceReference.GDSSendBulkeMailRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GDSSendBulkeMailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GDSSendBulkeMail", Namespace="http://tempuri.org/", Order=0)]
        public SBM.WebForms.SBMServiceReference.GDSSendBulkeMailRequestBody Body;
        
        public GDSSendBulkeMailRequest() {
        }
        
        public GDSSendBulkeMailRequest(SBM.WebForms.SBMServiceReference.GDSSendBulkeMailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GDSSendBulkeMailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string From;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string To;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string BCC;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CC;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Body;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string filePath;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string AppKey;
        
        public GDSSendBulkeMailRequestBody() {
        }
        
        public GDSSendBulkeMailRequestBody(string From, string To, string BCC, string CC, string Body, string Subject, string filePath, string AppKey) {
            this.From = From;
            this.To = To;
            this.BCC = BCC;
            this.CC = CC;
            this.Body = Body;
            this.Subject = Subject;
            this.filePath = filePath;
            this.AppKey = AppKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GDSSendBulkeMailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GDSSendBulkeMailResponse", Namespace="http://tempuri.org/", Order=0)]
        public SBM.WebForms.SBMServiceReference.GDSSendBulkeMailResponseBody Body;
        
        public GDSSendBulkeMailResponse() {
        }
        
        public GDSSendBulkeMailResponse(SBM.WebForms.SBMServiceReference.GDSSendBulkeMailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GDSSendBulkeMailResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GDSSendBulkeMailResult;
        
        public GDSSendBulkeMailResponseBody() {
        }
        
        public GDSSendBulkeMailResponseBody(string GDSSendBulkeMailResult) {
            this.GDSSendBulkeMailResult = GDSSendBulkeMailResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SendBulkeMailSoapChannel : SBM.WebForms.SBMServiceReference.SendBulkeMailSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SendBulkeMailSoapClient : System.ServiceModel.ClientBase<SBM.WebForms.SBMServiceReference.SendBulkeMailSoap>, SBM.WebForms.SBMServiceReference.SendBulkeMailSoap {
        
        public SendBulkeMailSoapClient() {
        }
        
        public SendBulkeMailSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SendBulkeMailSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendBulkeMailSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendBulkeMailSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SBM.WebForms.SBMServiceReference.GDSSendBulkeMailResponse SBM.WebForms.SBMServiceReference.SendBulkeMailSoap.GDSSendBulkeMail(SBM.WebForms.SBMServiceReference.GDSSendBulkeMailRequest request) {
            return base.Channel.GDSSendBulkeMail(request);
        }
        
        public string GDSSendBulkeMail(string From, string To, string BCC, string CC, string Body, string Subject, string filePath, string AppKey) {
            SBM.WebForms.SBMServiceReference.GDSSendBulkeMailRequest inValue = new SBM.WebForms.SBMServiceReference.GDSSendBulkeMailRequest();
            inValue.Body = new SBM.WebForms.SBMServiceReference.GDSSendBulkeMailRequestBody();
            inValue.Body.From = From;
            inValue.Body.To = To;
            inValue.Body.BCC = BCC;
            inValue.Body.CC = CC;
            inValue.Body.Body = Body;
            inValue.Body.Subject = Subject;
            inValue.Body.filePath = filePath;
            inValue.Body.AppKey = AppKey;
            SBM.WebForms.SBMServiceReference.GDSSendBulkeMailResponse retVal = ((SBM.WebForms.SBMServiceReference.SendBulkeMailSoap)(this)).GDSSendBulkeMail(inValue);
            return retVal.Body.GDSSendBulkeMailResult;
        }
    }
}
